"""empty message

Revision ID: 7e0b62e52595
Revises: dbdcd6fa5589
Create Date: 2021-04-11 18:14:59.623123

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0b62e52595'
down_revision = 'dbdcd6fa5589'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_Article_text', table_name='Article')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_Article_text', 'Article', ['text'], unique=False)
    # ### end Alembic commands ###
