"""Upgrade User Object

Revision ID: a5e33684a022
Revises: 121fa4996ba9
Create Date: 2021-03-29 12:33:40.475686

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e33684a022'
down_revision = '121fa4996ba9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Article', 'privacy_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint('Article_privacy_id_fkey', 'Article', type_='foreignkey')
    op.create_foreign_key(None, 'Article', 'PrivacySelection', ['privacy_id'], ['id'], onupdate='CASCADE')
    op.drop_constraint('PrivacySelection_owner_id_fkey', 'PrivacySelection', type_='foreignkey')
    op.drop_column('PrivacySelection', 'owner_id')
    op.drop_constraint('SentimentSelection_owner_id_fkey', 'SentimentSelection', type_='foreignkey')
    op.drop_column('SentimentSelection', 'owner_id')
    op.drop_constraint('Survey_owner_id_fkey', 'Survey', type_='foreignkey')
    op.drop_column('Survey', 'owner_id')
    op.add_column('User', sa.Column('username', sa.String(), nullable=True))
    op.create_index(op.f('ix_User_username'), 'User', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_User_username'), table_name='User')
    op.drop_column('User', 'username')
    op.add_column('Survey', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('Survey_owner_id_fkey', 'Survey', 'User', ['owner_id'], ['id'])
    op.add_column('SentimentSelection', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('SentimentSelection_owner_id_fkey', 'SentimentSelection', 'User', ['owner_id'], ['id'])
    op.add_column('PrivacySelection', sa.Column('owner_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('PrivacySelection_owner_id_fkey', 'PrivacySelection', 'User', ['owner_id'], ['id'])
    op.drop_constraint(None, 'Article', type_='foreignkey')
    op.create_foreign_key('Article_privacy_id_fkey', 'Article', 'PrivacySelection', ['privacy_id'], ['id'])
    op.alter_column('Article', 'privacy_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
