"""empty message

Revision ID: d3efc7e81b4b
Revises: 823a9e3627a9
Create Date: 2021-04-08 18:41:18.552691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd3efc7e81b4b'
down_revision = '823a9e3627a9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Survey', sa.Column('is_public', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Survey', 'is_public')
    # ### end Alembic commands ###
